<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<script type="text/javascript">
<?php if (Mage::helper('awmobile')->checkVersion('1.8.0.0')): ?>
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
<?php endif; ?>
var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
</script>
<form action="" id="co-payment-form">
    <?php echo $this->getChildChildHtml('methods_additional', '', true, true) ?>
    <?php echo $this->getChildHtml('methods') ?>
</form>
<?php echo $this->getChildChildHtml('additional') ?>
<div class="clear"></div>
    <div class="a-center">
        <div class="bottom-space">
            <span id="payment-buttons-container">
                <button type="button" class="form-button right" onclick="payment.save();"><span><?php echo $this->__('Continue') ?></span></button>
                <br />
                <span id="payment-please-wait" style="display:none;" class="opc-please-wait">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
                </span>
            </span>
        </div>
</div>

<script type="text/javascript">
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-400)+'px',
                left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }

    $$('.cvv-what-is-this').each(function(element){
        Event.observe(element, 'click', toggleToolTip);
    });
</script>
<script type="text/javascript">
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
</script>
