<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php foreach ($languages as $_code=>$_link): ?>
    <?php if($_link): ?>
        <a href="<?php echo $_link ?>"><img src="<?php echo $this->getSkinUrl('images/flag_<?php echo $_code ?>.gif') ?>" width="30" height="20" alt="<?php echo $_code ?>" /></a>
    <?php else: ?>
        <!--img src="<?php echo $this->getSkinUrl('images/flag_<?php echo $_code ?>.gif') ?>" width="30" height="20" alt="<?php echo $_code ?>"/-->
    <?php endif; ?>
<?php endforeach; ?>
