<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>


<?php if ($this->isEnabled()):?>
<div  id="aw_points-notification-box" >

    <h4><?php echo $this->__('Email Notification Settings') ?></h4>

    <form action="<?php echo $this->getAction() ?>" method="post" id="form-validate"> <?php echo $this->getBlockHtml('formkey') ?>

        <input  type="checkbox" id="aw_points-subscription" class="checkbox" name="is_subscribed" value="1" title="<?php echo $this->__('Subscribe to balance update') ?>"<?php if ($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?>  />
            <label for="aw_points-subscription">
                <?php echo $this->__('Subscribe to balance update') ?>
            </label>

        <div id="aw_points-button-to-subscribe">
                <button type="submit" title="<?php echo $this->__('Save Subscription Settings') ?>" class="form-button">
                    <span>
                        <?php echo $this->__('Save Subscription Settings') ?>
                    </span>
                </button>
        </div>

    </form>
    
</div>
<?php endif; ?>