<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php $_order = $this->getOrder() ?>
<!--<div class="page-head button-level">
    <h2><?php echo $this->__('My Orders - Details') ?></h2>
    <button class="form-button"><span><?php echo $this->__('Print All Shipments') ?></span></button>
</div>-->
<h3><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h3>
<?php $_shipment = $this->getShipment() ?>
<?php if($_shipment): ?>
    <?php $_shipments = array($_shipment); ?>
<?php else: ?>
    <?php $_shipments = $_order->getShipmentsCollection() ?>
<?php endif; ?>

<?php foreach ($_shipments as $_shipment): ?>
    <div class="divider"></div>
    <div class="head">
        <h3><?php echo $this->__('Shipment #%s', $_shipment->getIncrementId()) ?></h3>
    </div>
    <div class="col2-set">
        <div class="col-1">
            <h4><?php echo $this->__('Shipping Address') ?></h4>
            <?php $_shipping = $_shipment->getShippingAddress() ?>
            <address><?php echo $_shipping->format('html') ?></address>
        </div>
        <div class="col-2">
            <h4><?php echo $this->__('Billing Address') ?></h4>
            <?php $_billing = $_shipment->getbillingAddress() ?>
            <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
    </div>
    <br />
    <div class="col2-set">
        <div class="col-1">
            <h4><?php echo $this->__('Shipping Method') ?></h4>
             <?php echo $_order->getShippingDescription() ?>
             <?php if (count($_order->getTracksCollection()) > 0): ?>
                <table class="data-table">
                    <col />
                    <col />
                    <thead>
                        <tr>
                            <th><?php echo Mage::helper('sales')->__('Title')?></th>
                            <th><?php echo Mage::helper('sales')->__('Number')?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_order->getTracksCollection() as $track): ?>
                            <tr>
                                <td><?php echo $track->getTitle() ?></td>
                                <td><?php echo $track->getNumber() ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
        <div class="col-2">
            <h4><?php echo $this->__('Payment Method') ?></h4>
            <?php echo $this->getPaymentInfoHtml() ?>
        </div>
    </div>
    <br />
    <h4><?php echo $this->__('Items Ordered') ?></h4>
    <table cellspacing="0" class="data-table">
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th class="a-center" width="10%"><?php echo $this->__('SKU') ?></th>
                <th class="a-center" width="10%"><?php echo $this->__('Qty Shipped') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php $_items = $_shipment->getItemsCollection(); ?>
            <?php $_count = $_items->count(); ?>
            <?php $_index = 0; ?>
            <?php foreach ($_items as $_item): ?>
                <tr<?php echo ($_index++ > $_count ? ' class="last"' : '') ?>>
                <td>
                    <?php echo $this->htmlEscape($_item->getName()) ?>
                    <?php echo $this->htmlEscape($_item->getDescription()) ?>
                </td>
                <td class="a-center"><?php echo $this->htmlEscape($_item->getSku()) ?></td>
                <td class="a-center"><?php echo $_item->getQty()*1 ?></td>

            <?php endforeach; ?>
            </tr>
        </tbody>
    </table>
    <br />
<?php endforeach; ?>
<script type="text/javascript">window.print();</script>
