<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<div class="box account-nav">
    <div class="head">
        <h3><?php echo $this->__('My Account'); ?></h3>
    </div>
            <ul>
                <?php $_links = $this->getLinks(); ?>
                <?php $_index = 1; ?>
                <?php $_count = count($_links); ?>
                <?php foreach ($_links as $_link): ?>
                    <?php $_last = ($_index++ >= $_count); ?>
                    <?php if ($this->isActive($_link)): ?>
                        <li class="on<?php echo ($_last ? ' last' : '') ?>"><?php echo $_link->getLabel() ?></li>
                    <?php else: ?>
                        <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
</div>
