<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php
/**
 * Last order sidebar
 *
 * @see Mage_Sales_Block_Reorder_Sidebar
 */
?>
<?php $_items = $this->getItems()?>
<?php if($_items): ?>
<div class="box base-mini mini-compare-products">
<form method="post" action="<?php echo $this->getFormActionUrl() ?>" id="reorder-validate-detail">
    <div class="head">
        <h4 style="display: block; float: left;"><?php echo $this->__('My Orders') ?>&nbsp;&nbsp;-&nbsp;&nbsp;</h4>
        <a href="<?php echo $this->getUrl('customer/account') ?>"><?php echo $this->__('View All'); ?></a><br /><br />
        <h5><?php echo $this->__('Last ordered items') ?></h5>
    </div>
    <ol id="cart-sidebar-reorder">
    <?php $_showAddButtonFlag = false; ?>
    <?php foreach ($_items as $_item): ?>
        <li class="field-row">
            <div class="product-checkbox">
                <?php if ($this->isItemAvailableForReorder($_item)): ?>
                    <?php $_showAddButtonFlag = true; ?>
                    <input type="checkbox" name="products[]" value="<?php echo $_item->getProductId() ?>" class="validate-one-required-by-name" />
                <?php endif; ?>
            </div>
            <div class="product-names">
                <a href="<?php echo $this->getItemProductUrl($_item) ?>"><?php echo $this->getItemProductName($_item) ?></a>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <?php if ($_showAddButtonFlag): ?>
        <div class="actions">
            <button class="form-button" type="submit"><span><?php echo $this->__('Add to Cart') ?></span></button><br />
        </div>
    <?php endif; ?>
</form>
</div>
<?php echo $this->getPagerHtml(); ?>
<script type="text/javascript">
<!--
 var reorderFormDetail = new VarienForm('reorder-validate-detail');
//-->
</script>
<?php endif ?>
