<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
    <div class="page-head">
            <h3><?php echo $this->__('Order #%s (%s)', $order->getOrderId(), $order->getStatus()) ?></h3>
        </div>

    <div class="col2-set">
            <div class="col-1">
                <h4><?php echo $this->__('Billing Information') ?></h4>
                <address>
                        <?php echo $order->getAddressByType('billing')->toString('{{firstname}} {{lastname}}<br/>{{street}}<br/>{{city}}, {{regionName}} {{postcode}}<br/>T: 
                        {{telephone}}') ?>
                </address>
            </div>
            <div class="col-2">
                <h4><?php echo $this->__('Payment Method') ?></h4>
        <?php echo $this->getChildHtml('payment') ?>
            </div>
        </div>
    <p></p>
        <div class="col2-set">
            <div class="col-1">
                <h4><?php echo $this->__('Shipping Information') ?></h4>
                <address>
                        <?php echo $order->getAddressByType('shipping')->toString('{{firstname}} {{lastname}}<br/>{{street}}<br/>{{city}}, {{regionName}} {{postcode}}<br/>T: 
                        {{telephone}}') ?>
                </address></div>
            <div class="col-2">
                <h4><?php echo $this->__('Shipping Method') ?></h4>
                <?php echo $order->getShippingDescription() ?>
            </div>
        </div>
    <p></p>
    <?php $_items = $order->getEntitiesByType('item') ?>
    <table cellspacing="0" width="100%" class="data-table" id="my-orders-table">
  <!--      <thead>
            <tr>
                <th><?php echo $this->__('Items Order') ?></th>
                <th class="a-center"><?php echo $this->__('Qty') ?></th>
                <th class="a-right"><?php echo $this->__('Price') ?></th>
                <th class="a-right"><?php echo $this->__('Ext. Price') ?></th>
            </tr>
        </thead> -->
        <tfoot>
            <tr>
                <td class="a-right" colspan="4">
                    <?php echo $this->__('Grand Total: %s', $order->getGrandTotal()) ?>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach($_items as $_item): ?>
            <tr>
                <td><?php echo $this->htmlEscape($_item->getName()) ?></td>
                <td class="a-center"><?php echo $_item->getQty() ?></td>
                <td class="a-right"><?php echo $_item->getPrice() ?></td>
                <td class="a-right"><?php echo $_item->getRowTotal() ?></td>
            </tr>   
            <?php endforeach ?> 
        </tbody>
    </table>
<div>
    <a class="button grey left"  title="Go back" href="<?php echo Mage::getUrl('customer/account');?>"><span class="nowrap"><?php echo $this->__('Back');?></span></a>
</div>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
