<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php if(!empty($collection) && $collection->getSize()): ?>
    <div class="head">
        <h4><?php echo $this->__('Customer Reviews') ?></h4>
        <?php if($reviewCount): ?>
            <?php if( $this->getUseBackLink() ): ?>
            <small>&laquo; <a href="<?php echo $backLink ?>"><?php echo $this->__('Back') ?></a></small>
            <?php else: ?>
            <a href="<?php echo $reviewLink ?>"><small><?php echo $this->__('View All Reviews') ?></small></a>
            <?php endif; ?>
        <?php endif; ?>
        <span class="pipe">|</span>
        <a href="<?php echo $this->getAddLink() ?>#review-form"><small><?php echo $this->__('Add Your Review') ?></small></a>
    </div>
    <?php if( $this->getUseBackLink() ): ?>
    <?php echo $this->getToolbarHtml() ?>
    <?php endif; ?>
    <ol id="customer-reviews">
    <?php foreach ($this->getCollection() as $_review): ?>
        <li>
        <?php if( is_array($_review->getRatingVotes()->getItems()) && $this->getAverage($_review->getRatingVotes()) ): ?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getAverage($_review->getRatingVotes()) ?>%;"></div>
            </div>
        <?php endif; ?>
            <a href="<?php echo $_review->getReviewUrl() ?>" name="<?php echo $this->htmlEscape($_review->getTitle()) ?>"><strong><?php echo $this->htmlEscape($_review->getTitle()) ?></strong></a>
            <?php echo $this->__('Review by %s', $this->htmlEscape($_review->getNickname())) ?>
            <p class="no-padding"><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?></p>
        </li>
    <?php endforeach; ?>
    </ol>
    <?php if( $this->getUseBackLink() ): ?>
    <?php echo $this->getToolbarHtml() ?>
    <?php endif; ?>
<?php else: ?>
    <div class="head">
        <h4><?php echo $this->__('Customer Reviews') ?></h4>
    </div>
    <p><a href="<?php echo $reviewLink ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>
