<div id="text-class">
<div class="texttitle">Why Shop at OS-STore</div>
	<div id="textcontent">
		<div class="textcontentleft">
		<p class="text_blue">Wholesale Consumer Electronics</p>
		<p>Thank you for visiting os-store.com, where you will find thousands of products offered at reasonable wholesale prices and high quality. A quick look around our site will reveal our massive range of first-rate goods.All of our products are from Europe, Taiwanm, Hongkong and china, before shipping, our QC will carry out strict quality controls over our products, making sure that our customers receive goods of best quality.</p>
		</div>
		<div class="textcontentright">
		<p class="text_blue">Easy to order</P>
		<p>
		OS-STore.com makes paying for your orders easy by providing a range of convenient payment options. Below is a guide to the different payment methods used by OS-STore.com, so you can choose the right way for you.
		<br/><span style="color:red">Support main currency of world.</span>
		<br/><span style="color:blue">Paypal, Credit, Western Union, Bank Transfer</span>
		</P>
		</div>
	</div>



	<div id="textcontent">
		<div class="textcontentleft">
		<p class="text_blue">Fast delivery & Handle time</p>
		<p>We support shipping to world-wide, the package will be securely packed. Method of shipment include Fedex, DHL, UPS, TNT, EMS, Airmail/USPS, air / ocean bulk shipping. After clean payment the merchandise will be send out within 48 hr, and the fast delivery <span style="color:red">within 3days</span> of expedited service.</p>
		</div>
		<div class="textcontentright">
		<p class="text_blue">Quality First</P>
		<p>
		All of the products are brand new, top quality electronics: absolutely no closeouts, used electronics, or counterfeits. We offer you a wide-selection of consumer electronic products - all carefully selected with quality in mind, and quality controlled in our warehouse. This is your best opportunity to directly and safely access the Chinese electronics market - all in one place online, without the need to travel to China,Taiwan and Hk to find suppliers one by one.
		</P>
		</div>
	</div>

</div>


<?php /*
<div id="customerservice">
	<!-- begin of countries -->
	<div id="countries">
	    
	    <h1>OS-STORE International:</h1>
	    <ul>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/chinaFlag.gif"  border="0" /></a><a href="#">Simplified Chinese</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/taiwan_flag.jpg"  border="0" /></a><a href="#">Traditional Chinese</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/japan_flag.jpg"  border="0" /></a><a href="#">Japanese</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/korea_flag.jpg"  border="0" /></a><a href="#">Kroean</a></li>
		</ul>
		<ul>   
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/Thailand-Flag.jpg"  border="0" /></a><a href="#">Thai</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/india-flag.gif"  border="0" /></a><a href="#">Hindi</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/ArabicFlagTiny.png"  border="0" /></a><a href="#">Arabic</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/usa-flag.gif"  border="0" /></a><a href="#">English</a></li>
		</ul>
		<ul>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/flag-german.gif"  border="0" /></a><a href="#">Deutsch</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/France_flag.gif"  border="0" /></a><a href="#">Française</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/Italy_flag.jpg"  border="0" /></a><a href="#">Italiano</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/netherland_flag.gif"  border="0" /></a><a href="#">Nederlands</a></li>
		</ul>
		<ul> 
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/poland-flag.jpg"  border="0" /></a><a href="#">Polski</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/Russia_Flag.png"  border="0" /></a><a href="#">русский</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/spanish_flag.png"  border="0" /></a><a href="#">español</a></li>
		   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/portugal-flag.jpg"  border="0" /></a><a href="#">português</a></li>
		</ul>
		
	</div>
	<!-- end of countries -->
    
	
	<!-- begin of customercert -->
    <div class="customercert">
	 <ul>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/dhl.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/ems.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/fedex.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/tnt.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/usps.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/ups.gif"  border="0" /></a></li>
	 </ul>
	 <ul>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/paypal.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/visa.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/mastercard.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/xe.gif"  border="0" /></a></li>
	 </ul>
	 <ul>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/vb.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/ms.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/alipay.gif"  border="0" /></a></li>
	   
	 </ul>
	 <ul>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/sy.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/bbb.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/vs.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/tw.gif"  border="0" /></a></li>
	 </ul>
	 
	 <ul>
	   <li><a href="http://www.facebook.com/osstore/"><img src="<?php echo $this->getskinurl() ?>images/flags/f.gif"  border="0" /></a></li>
	   <li><a href="http://www.twitter.com/osstore/"><img src="<?php echo $this->getskinurl() ?>images/flags/t.gif"  border="0" /></a></li>
	   <li><a href="#"><img src="<?php echo $this->getskinurl() ?>images/flags/youtube.gif"  border="0" /></a></li>
	 </ul>
	</div>
	<!-- begin of customercert -->
	
</div>
*/ ?>