<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $this->getOrder())): ?>
<script type="text/javascript">
function giftMessageToogle(giftMessageIdentifier)
{
    var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
    var container = $('order-item-gift-message-'+giftMessageIdentifier);
    var row = $('order-item-row-'+giftMessageIdentifier);


    if(link.expanded) {
        link.expanded = false;
        link.removeClassName('collapse');
        link.addClassName('expand');
        if(container.hasClassName('last')) {
            row.addClassName('last');
        }
        container.hide();
    } else {
        link.expanded = true;
        link.addClassName('collapse');
        link.removeClassName('expand');
        if(container.hasClassName('last')) {
            row.removeClassName('last');
        }
        container.show();
    }

    return false;
}
</script>
<?php endif; ?>
<?php  $_order = $this->getOrder() ?>
<?php  if ($_order->getTracksCollection()->count()) : ?>
<div style="float:right">
<a href="#" id="linkId" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php echo $this->__('Track all shipment(s)') ?>"><?php echo $this->__('Track all shipments') ?></a>
</div>
<?php endif; ?>
<a href="<?php echo $this->getPrintAllShipmentsUrl($_order) ?>" target="_blank"><?php echo $this->__('Print All Shipments') ?></a>
<br />
<?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
<br />
<div class="head">
    <h3><?php echo $this->__('Shipment #') ?><?php echo $_shipment->getIncrementId(); ?></h3>
    <a href="<?php echo $this->getPrintShipmentUrl($_shipment) ?>" target="_blank"><?php echo $this->__('Print Shipment') ?></a>
</div>
<table class="data">
<?php $tracks = $_shipment->getTracksCollection(); ?>
<?php  if ($tracks->count()): ?>
    <tr>
        <td colspan="2">
            <a href="#" id="linkId" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_shipment) ?>','trackshipment','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php echo $this->__('Track this shipment') ?>"><?php echo $this->__('Track this shipment') ?></a>
        </td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->__('Tracking Number(s)') ?>:</td>
        <td>&nbsp;
    <?php
    $i = 1;
    $_size = $tracks->count();
    foreach($tracks as $track): ?>
    <?php if($track->isCustom()): ?>
        <?php echo $track->getNumber() ?>
    <?php else: ?>
    <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($track) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" ><?php echo $track->getNumber() ?></a>
    <?php endif; ?>
    <?php if($i!=$_size): ?>, <?php endif; ?>
    <?php $i++;
    endforeach; ?>
        </td>
    </tr>
<?php  endif; ?>
</table>
<h4><?php echo $this->__('Items Shipped') ?></h4>
<table cellspacing="0" class="data-table" id="my-orders-table-<?php echo $_shipment->getId(); ?>">
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th width="15%"><?php echo $this->__('SKU') ?></th>
            <th class="a-center" width="15%"><?php echo $this->__('Qty Shipped') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_items = $_shipment->getAllItems(); ?>
        <?php $_count = count($_items) ?>
        <?php $_index = 0; ?>
        <?php foreach ($_items as $_item): ?>
        <tr <?php echo ($_index++ > $_count ? ' class="last"' : '') ?> id="order-item-row-<?php echo $_item->getId() ?>">
            <td>
                <?php echo $this->htmlEscape($_item->getName()) ?>
                <?php echo $this->htmlEscape($_item->getDescription()) ?>
            </td>
            <td><?php echo $this->htmlEscape($_item->getSku()) ?></td>
            <td class="a-center"><?php echo $_item->getQty()*1 ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table-<?php echo $_shipment->getId(); ?>')</script>
<?php endforeach; ?>
<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back to My Orders') ?></a>
</div>
