<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="input-left">
    <h3><?php echo Mage::helper('customer')->__('Personal Information') ?></h3>
    <p>
        <?php echo $this->getCustomer()->toString('{{firstname}} {{lastname}}<br/>{{email}}') ?>
        <br/>
        <a href="<?php echo $this->getAccountUrl() ?>"><?php echo Mage::helper('customer')->__('Edit Personal Information') ?></a>
    </p>
    <h3><?php echo _('Newsletters') ?></h3>
    <?php echo $this->getSubscriptionText() ?>
    <p><a href="<?php echo $this->getManageNewsletterUrl() ?>"><?php echo Mage::helper('customer')->__('Edit Newsletter Subscription') ?></a></p>
</div>
<div class="input-right">
<h3><?php echo Mage::helper('customer')->__('Addresses') ?></h3>
<?php if($_addresses = $this->getPrimaryAddresses()): ?>
    <?php foreach ($_addresses as $_address): ?>
    <address>
        <?php echo $_address->toString("{{firstname}} {{lastname}}<br/>{{street}}<br/>{{city}}, {{regionName}} {{postcode}}<br/>T: {{telephone}}") ?>
        <br /><a href="<?php echo $this->getAddressEditUrl($_address) ?>"><?php echo Mage::helper('customer')->__('Edit Address') ?></a>
    </address>
    <?php endforeach; ?>
<?php endif; ?>
<a href="<?php echo $this->getAddressesUrl() ?>"><?php echo Mage::helper('customer')->__('Go to Address Book') ?></a>
</div>
<div class="clearfix"></div>

<div>
    <h3><?php echo Mage::helper('customer')->__('Last 5 Orders') ?></h3>
    <p>
    <?php echo Mage::helper('customer')->__('Order List...') ?><br/>
    <a href=""><?php echo Mage::helper('customer')->__('View Order List') ?></a>
    </p>
</div>

<div class="input-left">
    <h3><?php echo Mage::helper('customer')->__('Personal Information') ?></h3>
</div>

<?php if ($this->helper('wishlist')->isAllow()) : ?>
<div class="input-right">
    <h3><?php echo Mage::helper('customer')->__('My Wishlist') ?></h3>
</div>
<?php endif; ?>

<div class="input-left">
    <h3><?php echo Mage::helper('customer')->__('My Reviews') ?></h3>
</div>

<div class="input-right">
    <h3><?php echo Mage::helper('customer')->__('My Tags') ?></h3>
</div>

<div class="input-left">
    <h3><?php echo Mage::helper('customer')->__('Last Viewed Items') ?></h3>
</div>

<div class="input-right">
    <h3><?php echo Mage::helper('customer')->__('Shopping Cart') ?></h3>
</div>
