<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<div class="checkout-onepage-payment-additional-giftcardaccount">
<p class="note">
    <?php $_url = $this->getUrl('')."#cart"; ?>
    <?php echo Mage::helper('enterprise_giftcardaccount')->__('To add or remove gift cards, <a href="%s">click here</a>.', $_url); ?><br />

    <?php if ($this->getAppliedGiftCardAmount()): ?>
        <?php $amount = Mage::helper('core')->currency($this->getAppliedGiftCardAmount(), true); ?>
        <?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card amount applied to order: %s', $amount); ?>
    <?php endif; ?>
</p>
</div>
