<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<div class="search-form" id="topSearch" style="">
    <div class="search-form-cont">
        <div class="col2-set">
            <form id="search_mini_form" name="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
            <div class="col-1 search-md">
                <div class="search-st"><div class="search-end">
                    <input  id="search" type="text" class="input-text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" autocapitalize />
                </div></div>
            </div>
            <div class="col-2">
                <a class="search-close" href="javascript:void(0);" onclick="hideSearchForm(); return false;">&nbsp;</a>
            </div><div class="clear"></div>
            </form>
        </div>
    </div>
    
</div>
<div class="search-overlay" id="topSearchOverlay">
    <div class="cart-loader">
        <span>
            <img src="<?php echo $this->getSkinUrl('images/cart-ajax-loader.gif'); ?>" alt="<?php echo $this->__('Loading...'); ?>" />
        </span>
    </div>    
    
</div>

