<div id="text_info">
	 
	 <h3 class="in_1em"><a name="#a"></a>为何选择OS商城？</h3>
		<ul>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/store.png') ?>" /></div>
		<div style="float:right;width:88%"><b>简单又安全的线上购物</b><br /> 
		<span>多种付款方式和简单的购物流程。</span></div>
		</li>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/offter.png') ?>" /></div>
		<div style="float:right;width:88%"><b>更多的安全和快速的购物选择~让生活更美好</b> <br />
<span>提供完整的产品资讯和特殊的货源，甚至只有OS商城独有。</span></div>
		</li>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/os.png') ?>" /></div>
		<div style="float:right;width:88%"><b>安全快速的付款方式</b><br />
		<span>简单、快速、机密付款技术，全时段妥善保管你的讯息资料。</span></div>
		</li>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/fly.png') ?>" /></div>
		<div style="float:right;width:88%"><b>世界各地快速交货</b> <br />
		<span>佣用国际依赖的物流服务商合作，世界各地最快可3天之内送达。</span></div>
		</li>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/high.png') ?>" /></div>
		<div style="float:right;width:88%"><b>世界标准的高品质</b><br />
		<span>每一个产品都经过全面的测式和品质控制程序。</span></div>
		</li>	
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/life.png') ?>" /></div>
		<div style="float:right;width:88%"><b>加入OS商城到你的生活中吧！！
		 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="button" class="button" onclick="window.location='<?php echo $this->getUrl('customer/account/login') ?>';">
		<span><span><?php echo $this->__('加入我们') ?></span></span></button>
		</b><br />
		<span>注册成为我们的会员，为你提供更多的服务、资讯、折扣。</span></div>
		</li>
		</ul>
		
		
</div>

