<?php if ($_products = $this->getProducts()): ?>
<p><h3><?php echo $this->__('Special Offer') ?></h3></p>
<table>
<?php $_columnCount = $this->getColumnCount(); ?>
<?php $i=0; foreach ($_products as $_product): ?>
    <?php if ($i++%$_columnCount==0): ?>
    <tr>
	<?php endif ?>
        <td align="middle">
		    <p>
			   <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" border="0"  height="135" width="135" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
			</p>

            <p>
			  <a href="<?php echo $_product->getProductUrl() ?>"><strong><?php echo $this->htmlEscape($_product->getName()) ?></strong></a>
			 </p>
            
            <p>
                <?php echo $this->__('Regular Price:') ?> <strong style="text-decoration:line-through;"><?php echo Mage::helper('core')->currency($_product->getPrice()) ?></strong><br />
                <strong><?php echo $this->__('Special price:') ?> <span style="color:#FF0000;"><?php echo Mage::helper('core')->currency($_product->getSpecialPrice()) ?></span></strong>
           </p>
           
        </td>
	<?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </tr>
     <?php endif ?>
   
<?php endforeach; ?>
</table>
<?php endif; ?>
