<div class="mageasia_tags_widget">

	<?php 
    
    echo $this->getChildHtml("azbar"); 
    
    ?>
    
    <h1 class="tagheadh1">Latest Tags</h1>
     
    <div class="tagslist">
       <div class="tagsitemlist"><ul>
	<?php
	$tagslist=$this->getLatestTags();
	
	foreach($tagslist as $item){
		$url=Mage::helper("lbtags")->makeTagsUrl($item->getIdentifier()); 
		$title=$item->getName();
		
		 
	?>
    <li>
    	<a href="<?php echo $url;?>" title="<?php echo $title;?>"><?php echo $title;?></a>
    </li>
    <?php
	}
	?>

</ul>
</div>
    
    </div>

</div>