<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
    <fieldset class="newsletter">
        <h2 class="accent"><?php echo $this->__('Newsletter') ?></h2>
        <form action="<?php echo $this->getUrl('newsletter/subscriber/new') ?>" method="post" id="newsletter-validate">
                <fieldset>
                        <legend><?php echo $this->__('Newsletter') ?></legend>
                        <label for="newsletter"><?php echo $this->__('Sign up for our newsletter') ?>:</label>
                        <input name="email" id="newsletter" type="text" class="required-entry validate-email input-text" />
                        <input type="submit" value="<?php echo $this->__('Submit') ?>" alt="<?php echo $this->__('Subscribe') ?>" class="input-button" />
                </fieldset>
        </form>
        <script type="text/javascript">
        <!--
            var newsletterSubscriberForm = new VarienForm('newsletter-validate');
        //-->
        </script>
    </fieldset>
