<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php
/**
 * Create account form template
 *
 * @see Mage_Customer_Block_Form_Register
 */
?>
<div class="page-head"><h2><?php echo $this->__('Create an Account') ?></h2></div>
<div class="adres-data-info"><div class="login-box">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <fieldset class="group-select wide">
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h4 class="legend"><?php echo $this->__('Personal Information') ?></h4>
            <ul class="form-list">
                <li>
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml() ?>
                </li>
                <li>
                    <div><label for="email_address"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label></div>
                    <div class="input-box"><input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="validate-email required-entry input-text" /></div>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li>
                    <div class="a-right">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" <?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif ?> />
                        <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    </div>
                </li>
                <?php endif ?>
<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
<?php if ($_dob && ($_dob->isEnabled())): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
<?php endif ?>
<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
<?php if ($_taxvat && ($_taxvat->isEnabled())): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
<?php endif ?>
<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
<?php if ($_gender && ($_gender->isEnabled())): ?>
    <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
<?php endif ?>
            </ul>
        </fieldset>
        <?php if($this->getShowAddressFields()): ?>
        <input type="hidden" name="create_address" value="1" />
        <fieldset class="group-select wide">
            <h4 class="legend"><?php echo $this->__('Address Information') ?></h4>
            <ul>
                <li>
                        <div><label for="company"><?php echo $this->__('Company') ?></label></div>
                        <div class="input-box"><input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" /></div>
                </li>
                <li>
                        <div><label for="telephone"><?php echo $this->__('Telephone') ?> <span class="required">*</span></label></div>
                        <div class="input-box"><input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="required-entry input-text" /></div>
                </li>
                <li>
                        <div><label for="street_1"><?php echo $this->__('Street Address') ?> <span class="required">*</span></label></div>
                        <div class="input-box"><input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="required-entry input-text" /></div>
                </li>
                <li>
                        <div class="input-box"><input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address %s', 2) ?>" id="street_2" class="input-text" /></div>
                </li>
                <li>
                        <div><label for="city"><?php echo $this->__('City') ?> <span class="required">*</span></label></div>
                        <div class="input-box"><input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="required-entry input-text" id="city" /></div>
                </li>
                <li>
                        <div><label for="region_id"><?php echo $this->__('State/Province') ?> <span class="required">*</span></label></div>
                        <div>
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                                $('region_id').setAttribute('defaultValue',  "<?php echo $this->getFormData()->getRegionId() ?>");
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none" />
                        </div>
                </li>
                <li>
                        <div><label for="zip"><?php echo $this->__('Zip/Postal Code') ?> <span class="required">*</span></label></div>
                        <div class="input-box"><input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="validate-zip-international required-entry input-text" /></div>
                </li>
                <li>
                        <div><label for="country"><?php echo $this->__('Country') ?> <span class="required">*</span></label></div>
                        <div><?php echo $this->getCountryHtmlSelect() ?></div>
                </li>
            </ul>
        </fieldset>
        <input type="hidden" name="default_billing" value="1" />
        <input type="hidden" name="default_shipping" value="1" />
        <?php endif; ?>
        <fieldset class="group-select wide">
            <h4 class="legend"><?php echo $this->__('Login Information') ?></h4>
            <ul class="form-list">
                <li>

                        <div><label for="password"><?php echo $this->__('Password') ?> <span class="required">*</span></label></div>
                        <div class="input-box"><input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="required-entry validate-password input-text" /></div>
                </li>
                <li class="last">
                        <div><label for="confirmation"><?php echo $this->__('Confirm Password') ?> <span class="required">*</span></label></div>
                        <div  class="input-box"><input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="required-entry validate-cpassword input-text" /></div>
                </li>
            </ul>
        </fieldset>
               <p class="a-right required"><?php echo $this->__('* Required Fields') ?></p>
               <div class="a-center">
                    <button class="form-button" type="submit"><span><?php echo $this->__('Submit') ?></span></button><br />
               </div>
    </form>
</div></div>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
    <?php if($this->getShowAddressFields()): ?>
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    <?php endif ?>
</script>
