<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
/* @var $this Mage_Reports_Block_Product_Compared */
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="box base-mini mini-compare-products">
    <div class="head">
        <h4><span><?php echo $this->__('Recently Compared Products') ?></span></h4>
    </div>
    <div class="content">
        <ol  id="recently-compared-items">
        <?php foreach ($_products as $_item): ?>
            <li><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a></li>
        <?php endforeach; ?>
        </ol>
    </div>
    <script type="text/javascript">
    decorateList('recently-compared-items')
    </script>
</div>
<?php endif; ?>
