<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php
/**
 * Product list toolbar
 * @see AW_Mobile_Block_Catalog_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize() && ($this->getCollection()->getSize() > $this->getLimit()) ): ?>
<div class="product-list-toolbar">
    <ul class="pager">
        <li class="first">
            <?php if (!$this->isFirst()): ?>
            <a class="button pager left" href="<?php echo $this->getPreviousPageUrl(); ?>"><?php echo $this->__('Prev'); ?></a>
            <?php endif; ?>
        </li>
        <li class="middle"><span><nobr><?php echo $this->__('Page %s of %s', $this->getCurrentPage(), $this->getLastPageNum()) ?></nobr></span></li>
        <li class="last">
            <?php if (!$this->isLast()): ?>
            <a class="button pager right" href="<?php echo $this->getNextPageUrl(); ?>"><?php echo $this->__('Next'); ?></a>
            <?php endif; ?>
        </li>
    </ul>
</div>
<div class="clear"></div>
<?php endif ?>
