<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
/* @var $this Mage_Wishlist_Block_Share_Email_Items */
?>
<?php $l = $this->getWishlistItemsCount() ?>
<div style="border:1px solid #BEBCB7; padding:15px; background:#F8F7F5;">
<table cellspacing="0" cellpadding="0">
    <tr>
    <?php $i = 0; foreach($this->getWishlistItems() as $item): $i++ ?>
        <td width="32%">
            <p align="center"><a href="<?php echo $this->getProductUrl($item) ?>"><img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize(135); ?>" style="border:1px solid #ccc;" width="135" alt="" /></a></p>
            <p align="center"><a href="<?php echo $this->getProductUrl($item) ?>" style="color:#203548;"><strong><?php echo $this->htmlEscape($item->getName()) ?></strong></a></p>
            <?php if($this->hasDescription($item)): ?><p align="center"><?php echo $this->__('Comment') ?>:<br /><?php echo $this->getEscapedDescription($item) ?></p><?php endif; ?>
            <p align="center"><a href="<?php echo $this->getProductUrl($item) ?>" style="color:#1E7EC8;"><?php echo $this->__('View Product') ?></a> <small>
            <?php if ($item->getIsSalable()):?>|</small> <a href="<?php echo $this->getAddToCartUrl($item) ?>" style="color:#DC6809;"><strong><?php echo $this->__('Add to Cart') ?></strong></a><?php endif;?>
            </p></td>
        <?php if ($i%3!=0): ?>
            <td width="2%"></td>
        <?php else: ?>
           </tr>
            <tr>
                <td colspan="5">&nbsp;</td>
            </tr>
            <?php if ($i<$l): ?>
               <tr>
            <?php endif ?>
        <?php endif ?>
    <?php endforeach ?>
</table>
</div>
