<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<div>
    <div class="dashboard-block">
        <div class="page-head">
            <h3><?php echo $this->__('Contact Information') ?></h3>
            <a class="edit" href="<?php echo $this->getUrl('customer/account/edit') ?>"><img src="<?php echo $this->getSkinUrl('images/edit.gif') ?>" alt="<?php echo $this->__('Edit') ?>" /></a>
        </div>
        <div class="content">
            <?php echo $this->htmlEscape($this->getCustomer()->getFirstname()) ?>
            <?php echo $this->htmlEscape($this->getCustomer()->getLastname()) ?><br />
            <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
            <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
        </div>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="dashboard-block">
        <div class="page-head">
            <h3><?php echo $this->__('Newsletters') ?></h3>
            <a class="edit" href="<?php echo $this->getUrl('newsletter/manage') ?>"><img src="<?php echo $this->getSkinUrl('images/edit.gif') ?>" alt="<?php echo $this->__('Edit') ?>" /></a>
        </div>
        <div class="content">
            <?php if( $this->getIsSubscribed() ): ?>
                <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
            <?php else: ?>
                <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
</div>