<div class="home_amy">
	<div class="top_seller_amy">
		<div class="product_name">
		<div class="title_amy">Recommend Products</div>
		<div class="more_amy"><a href="category/">More>></a></div>
		</div>

<table cellpadding="0" cellspacing="0" border="0" width="100%;" class="recommend_amy">
<tr>
<td colspan="4" height="20px" align="center"></td>
</tr>
<tr>
<td width="25%"  align="center"><a href="computer/hard-disk-drive.html"><img src="images/home/apple.gif" border="0"  /></a></td>
<td width="25%" align="center"><a href="wireless-card.html"><img src="images/home/3gwifi.gif" border="0"  /></a></td>
<td width="25%" align="center"><a href="computer.html"><img src="images/home/computer.gif" border="0"  /></a></td>
<td width="25%" align="center"><a href="cell-phone-pda/mobile-phone.html"><img src="images/home/mobilephone.gif" border="0"  /></a></td>
</tr>


<tr>
<td align="center"><a href="computer/hard-disk-drive.html">HDD</a></td>
<td align="center"><a href="wireless-card.html">3G & Wireless Card</a></td>
<td align="center"><a href="computer.html">Computer</a></td>
<td align="center"><a href="cell-phone-pda/mobile-phone.html">Mobile Phone</a></td>
</tr>



<tr>
<td colspan="4" height="20px" align="center"></td>
</tr>



<tr>
<td width="25%"  align="center"><a href="video-game.html"><img src="images/home/videogame.gif" border="0"  /></a></td>
<td width="25%" align="center"><a href="computer/cpu.html"><img src="images/home/intelcpu.gif" border="0"  /></a></td>
<td width="25%" align="center"><a href="catalogsearch/result/index/?q=AMD+CPU&order=name&dir=asc"><img src="images/home/amdcpu.gif" border="0"  /></a></td>
<td width="25%" align="center"><a href="ic-chipset.html"><img src="images/home/icchipset1.gif" border="0"  /></a></td>
</tr>

<tr>
<td align="center"><a href="video-game.html">Video Game</a></td>
<td align="center"><a href="computer/cpu.html">Intel CPU</a></td>
<td align="center"><a href="catalogsearch/result/index/?q=AMD+CPU&order=name&dir=asc">AMD CPU</a></td>
<td align="center"><a href="ic-chipset.html">IC Chipset</a></td>
</tr>



</table>




		<div class="clear"></div>	
	</div>


</div>
