<div class="block2">
			<ul class="follow_box">
				<li><span style="font-size:14px;margin-left:10px;"><strong>Follow Us</strong></span></li>
				
				<div class="blog">
					<a class="blog-title-picture" href="http://blog.os-store.com"  >
					  <?php echo Mage::getStoreConfig('blog/blog/title'); ?>
					</a>
				</div>
				
					<ul class="follow_us">
						<li><a rel="nofollow"
							class="icn fb"
							href="https://www.facebook.com/osstore001">facebook</a></li>
						<li><a rel="nofollow"
							class="icn b"
							href="http://osstore.blog.com/">blog</a></li>
						<li><a rel="nofollow"
							class="icn tw"
							href="hhtp://www.twitter.com/osstore/">twitter</a></li>
						<li><a rel="nofollow"
							class="icn tb"
							href="http://www.youtube.com/osstore">youtube</a></li>

						<li><a rel="nofollow"
							class="icn g"
							href="<?php echo $this->getbaseurl() ?>">google+</a></li>
					</ul>
					
			</ul>
				
</div>


