<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
/* @var $this Mage_Reports_Block_Product_Compared */
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="box recently">
<h3><?php echo $this->__('Your Recently Compared') ?></h3>
<table cellspacing="0" class="recently-list" id="recently-compared-list-table">
<tr>
<?php $i=0; foreach ($_products as $_product): ?>
    <?php if ($i>5): continue; endif; ?>

    <td>
        <div>
            <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->helper('awmobile')->stripTags($_product->getName(), null, true) ?>">
                <img class="product-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(80, 77) ?>" width="80" height="77" alt="<?php echo $this->helper('awmobile')->stripTags($_product->getName(), null, true) ?>" />
            </a>
        </div>
            <p><a class="product-name" href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->helper('awmobile')->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
            <?php echo $this->getPriceHtml($_product, true, '-home-compared') ?>
            <?php if($_product->isSaleable()): ?>
                <button type="button" class="form-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
            <?php else: ?>
                <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
            <?php endif; ?>
            <div class="clear"></div>
            <p class="add-to">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-cart"><?php echo $this->__('Add to Wishlist') ?></a>
                <?php endif; ?>
                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?><br />
                <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
                <?php endif; ?>
            </p>
        </td>
<?php $i++; endforeach; ?>
<?php for($i;$i%5!=0;$i++): ?>
        <td>&nbsp;</td>
    <?php endfor ?>
    </tr>
</table></div>
<?php endif; ?>
