<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<div class="page-head">
    <h3><?php echo $this->__('RSS Feeds') ?></h3>
</div>
<?php
$_categories = $this->getRssCatalogFeeds();
$_misc = $this->getRssMiscFeeds();
?>
    <?php if($_misc): ?>
    <table cellspacing="0" class="data-table" id="rss-table-misc">
        <thead><tr><th><?php echo $this->__('Miscellaneous Feeds') ?></th></tr></thead>
        <tbody>
    <?php foreach ($_misc as $_feed): ?>
            <tr>
                <td class="a-left"><span class="left"><?php echo $_feed->getLabel() ?></span><a href="<?php echo $_feed->getUrl() ?>" class="link-feed"><?php echo $this->__('Get Feed'); ?></a></td>
            </tr>
    <?php endforeach; ?>
         </tbody>
    </table>
    <?php endif; ?>
    <?php if ($_categories || $_misc): ?><br/><?php endif ?>
    <?php if($_categories): ?>
    <table cellspacing="0" class="data-table" id="rss-table-category">
    <thead><tr><th><?php echo $this->__('Category Feeds') ?></th></tr></thead>
    <tbody>
    <?php foreach ($_categories as $_category): ?>
    <tr>
        <td class="a-left"><span class="left"><?php echo $_category->getLabel() ?></span><a href="<?php echo $_category->getUrl() ?>" class="link-feed"><?php echo $this->__('Get Feed'); ?></a></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('rss-table-misc'); decorateTable('rss-table-category')</script>
<?php else: ?>
<p><?php echo $this->__('There are no Rss Feeds.'); ?></p>
<?php endif; ?>
