<div class="page-head-alt button-level">
    <h3><?php echo $this->__('Review and Commit to Buy') ?></h3>
</div>

<?php  $_product = $this->getProduct();?>
<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
<input type="hidden" id="isbuynow" name= "isbuynow" value="0" />

<?php
//var_dump($_POST);
function dumpOption($values,$prefix)
{

foreach($values as $key=>$value)
{

if(is_array($value))
{
   dumpOption($value,$key);
}
else
{
if(!empty($prefix))
{
$name = $prefix . "[" . $key . "]";
}
else
{
$name = $key;
}
echo '<input type="hidden"  name= "'. $name . '" value="' . $value . '" />'
 . "\n";
}
}
}

dumpOption($_POST,"");
?>

<div style="height:35px;margin-left:3px;"><img src="<?php echo $this->GetSkinUrl('images/choice-cart.gif') ?>" width="950" height="35"></div>
  <table width="950" border="0" cellpadding="0" cellspacing="1" style="background:#D9DDE3;margin-left:3px;">
    <tr style="background:#f4f4f4; height:30px;font-weight:bold;">
      <td align="center" >Product images </td>
      <td align="center" >Product Name </td>
      <td align="center" >Price</td>
      <td align="center" >Shipping and handing</td>
      <td align="center" >Payment methods</td>
    </tr>
    <tr style="background:#ffffff;">
      <td style="width:15%;padding:10px;">
				<a href="<?php echo $_product->getProductUrl() ?>">
				<img width="100" border="0" alt="" class="product-img"
				src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(100); ?>" 
				alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
	  </td>
      <td style="width:30%;padding:5px;">
		<a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
	  </td>
      <td style="width:10%;padding:5px;">					
		<?php echo $this->getPriceHtml($_product) ?><?php if(!empty($_POST["qty"])) echo "( x {$_POST["qty"]})";?>
	  </td>
      <td style="width:25%;padding:5px;">				
		  <?php if ($_shippinghandle = $this->getChildHtml('shippinghandle')):?>
		  <?php echo $_shippinghandle ?><?php endif;?>
	  </td>
      <td style="width:20%;padding:5px;">PayPal /Cradit Card or Western Union / Bank Transfer</td>
    </tr>
    <tr>
      <td height="40" colspan="5" style="background:#DEE5E8;padding:10px;">
	  By Clicking on the button below, you commit to buy this item from the seller
		<div style="float:right;">
		<button type="button" class="form-button" onclick="$('isbuynow').value = 1; productAddToCartForm.submit()">
		<span><?php echo $this->__('Commit to buy') ?></span></button>
		<span class="pipe" style="float:left" ></span>
		&nbsp;&nbsp; 
		<button type="button" class="form-button" onclick="productAddToCartForm.submit()">
		<span><?php echo $this->__('Add to Cart') ?></span></button>
		</div>
	</td>
    </tr>
  </table>

<div class="product-buychoice-bottom" style="margin:10px;">
	<b>You are Agreeing to a contract</b> -- You will enter into a legally binding contract to purchase the item from the seller. You are responsible for reading the full item listing, including the seller's instructions and accepted payment methods, Seller assumes all responsibility for listing the item
</div>



</form>
<script type="text/javascript">
            /*var productAddToChoiceForm = new VarienForm('product_addtocart_form');
            
            productAddToChoiceForm.submit = function(){
                    if (this.validator.validate()) {
                    	  productAddToChoiceForm.form.action = "<?php echo $this->getAddToChoiceUrl($_product);?>";
                          this.form.submit();
                    }
            }.bind(productAddToChoiceForm);
		*/

            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(){
                    if (this.validator.validate()) {
                            this.form.submit();
                    }
            }.bind(productAddToCartForm);
            
            var productBuyNowForm = new VarienForm('product_buynow_form');
            productBuyNowForm.submit = function(){
                    if (this.validator.validate()) {
                            this.form.submit();
                    }
            }.bind(productBuyNowForm);
    </script>
