
        
<div class="footer-block first">
<h6>Customer Service</h6>
<ul>
<li><a href="about-magento-store/">About Us</a></li>
<li><a href="our-company/">Our company</a></li>
<li><a href="catalog/seo_sitemap/category/">Sitemap</a></li>
</ul>

</div>
<div class="footer-block">
<h6>Customer Info</h6>
<ul>
<li><a href="contacts/">Contact Us</a></li>
<li><a href="price-matching/">Price matching</a></li>
<li><a href="testimonials/">Testimonials</a></li>
</ul>
</div>

<div class="footer-block">
<h6>Corporate</h6>
<ul>
<li><a href="privacy/">Privacy Policy</a></li>
<li><a href="safe-shopping/">Safe &amp; secure shopping</a></li>
<li><a href="terms/">Terms &amp; conditions</a></li>
</ul>

</div>

<div class="footer-block last">
<h6>Information</h6>

<ul>
<li><a href="delivery/">Delivery information</a></li>
<li><a href="guarantee/">Satisfaction guarantee</a></li>
<li><a href="returns/">Returns policy</a></li>
</ul>
</div>  

        
                                   