<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php if(isset($poll)) : ?>

<script type="text/javascript">
    function validatePollAnswerIsSelected()
    {
        var options = $$('input.poll_vote');

        for( i in options ) {
            if( options[i].checked == true ) {
                return true;
            }
        }
        return false;
    }
</script>

<div class="box base-mini mini-poll">
    <div class="head">
        <h4><span><?php echo $this->__('Community Poll') ?></span></h4>
    </div>
    <form id="pollForm" action="<?php echo $action ?>" method="post" onsubmit="return validatePollAnswerIsSelected();">
        <div class="content">
            <h5><?php echo $this->htmlEscape($poll->getPollTitle()); ?></h5>
            <?php if( $poll_answers ): ?>
                    <table cellspacing="2">
                        <tbody>
                            <?php foreach( $poll_answers as $answer ): ?>
                            <tr>
                                <td><input type="radio" name="vote" class="poll_vote" id="vote_<?php echo $answer->getId() ?>" value="<?php echo $answer->getAnswerId() ?>" /></td>
                                <td><label for="vote_<?php echo $answer->getId() ?>"><?php echo $this->htmlEscape($answer->getAnswerTitle()) ?></label>&nbsp;</td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
            <?php endif; ?>
        </div>
        <div class="actions"><button class="form-button-alt right" type="submit"><span><?php echo $this->__('Vote') ?></span></button></div>
    </form>
</div>
<?php endif; ?>
