<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>

<?php
/**
 * @see Enterprise_Reward_Block_Customer_Reward_Settings
 */
?>
<form action="<?php echo $this->getUrl('reward/customer/saveSettings') ?>" method="post" id="form-validate">
<div class="account-block">
    <?php echo $this->getBlockHtml('formkey')?>
    <h4 class="legend"><?php echo $this->__('Email Notification Settings'); ?></h4>
    <ul class="form-list">
        <li class="control">
            <span class="input-box"><input type="checkbox" name="subscribe_updates" id="subscribe_updates" value="1" title="<?php echo $this->__('Subscribe for balance updates') ?>"<?php if($this->isSubscribedForUpdates()): ?> checked="checked"<?php endif; ?> class="checkbox" /></span><label for="subscribe_updates"><?php echo $this->__('Subscribe for balance updates') ?></label>
        </li>
        <li class="control">
            <span class="input-box"><input type="checkbox" name="subscribe_warnings" id="subscribe_warnings" value="1"<?php if($this->isSubscribedForWarnings()): ?> checked="checked"<?php endif; ?> class="checkbox" /></span><label for="subscribe_warnings"><?php echo $this->__('Subscribe for points expiration notifications') ?></label>
        </li>
    </ul>
</div>
<div class="button-space a-center">
    <button type="submit" class="form-button form-button-alt giftcard" title="<?php echo $this->__('Save Subscription Settings') ?>"><span><span><?php echo $this->__('Save Subscription Settings') ?></span></span></button>
</div>
</form>
