<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php
/**
 * @see Mage_Paypal_Block_Express_Shortcut
 */
?>
<div class="paypal-logo-container">
    <p class="paypal-logo">
    <?php $shortcutHtmlId = $this->getShortcutHtmlId() ?>
    <?php if ($this->getIsInCatalogProduct()): ?>
    <?php endif; ?>
    <a id="<?php echo $shortcutHtmlId ?>" href="<?php echo $this->getCheckoutUrl()?>"><img src="<?php echo $this->getImageUrl()?>" alt="<?php echo Mage::helper('paypal')->__('Checkout with PayPal');?>" /></a>
    <?php if (!$this->getIsInCatalogProduct()): ?>
    
    <?php endif; ?>
    <?php if ($this->getConfirmationUrl() || $this->getIsInCatalogProduct()): ?>
    <?php if ($this->getIsInCatalogProduct()): ?>
        <input type="hidden" id="pp_checkout_url" name="return_url" value="" />
    <?php endif; ?>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartFormForPayPalButton = new VarienForm('product_addtocart_form');
        productAddToCartFormForPayPalButton.form.action = '<?php echo $this->helper('checkout/cart')->getAddUrl(Mage::registry('current_product')) ?>';
        Event.observe('<?php echo $shortcutHtmlId ?>', 'click', function(event) {
            <?php if ($this->getConfirmationUrl()): ?>
                if (confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->getConfirmationMessage())?>')) {
                    this.href = '<?php echo $this->getConfirmationUrl() ?>';
                }
            <?php endif; ?>
            <?php if ($this->getIsInCatalogProduct()): ?>
                $('pp_checkout_url').value = this.href;
                productAddToCartFormForPayPalButton.submit(this);
                event.stop();
            <?php endif; ?>
        });
    //]]>
    </script>
    <?php endif; ?>
    </p>
</div>