<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $this->getOrder())): ?>
<script type="text/javascript">
function giftMessageToogle(giftMessageIdentifier)
{
    var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
    var container = $('order-item-gift-message-'+giftMessageIdentifier);
    var row = $('order-item-row-'+giftMessageIdentifier);


    if(link.expanded) {
        link.expanded = false;
        link.removeClassName('collapse');
        link.addClassName('expand');
        if(container.hasClassName('last')) {
            row.addClassName('last');
        }
        container.hide();
    } else {
        link.expanded = true;
        link.addClassName('collapse');
        link.removeClassName('expand');
        if(container.hasClassName('last')) {
            row.removeClassName('last');
        }
        container.show();
    }

    return false;
}
</script>
<?php endif; ?>
<?php  $_order = $this->getOrder() ?>
<a href="<?php echo $this->getPrintAllCreditmemosUrl($_order) ?>" target="_blank"><?php echo $this->__('Print All Refunds') ?></a>
<?php foreach ($_order->getCreditmemosCollection() as $_creditmemo): ?>
<br />
<div class="head">
    <h3><?php echo $this->__('Refund #') ?><?php echo $_creditmemo->getIncrementId(); ?></h3>
    <a href="<?php echo $this->getPrintCreditmemoUrl($_creditmemo) ?>" target="_blank"><?php echo $this->__('Print Refund') ?></a>
</div>
<h4><?php echo $this->__('Items Refunded') ?></h4>
<table cellspacing="0" class="data-table" id="my-orders-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th width="10%"><?php echo $this->__('SKU') ?></th>
            <th width="10%"><?php echo $this->__('Price') ?></th>
            <th class="a-center" width="5%"><?php echo $this->__('Qty') ?></th>
            <th><?php echo $this->__('Subtotal') ?></th>
            <th class="wrap" width="7%"><?php echo $this->__('Tax Amount') ?></th>
            <th class="wrap" width="7%"><?php echo $this->__('Discount Amount') ?></th>
            <th class="wrap"><?php echo $this->__('Row Total') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_items = $_creditmemo->getAllItems(); ?>
        <?php $_count = count($_items); ?>
        <?php $_index = 0; ?>
        <?php foreach ($_items as $_item): ?>
            <tr <?php echo ($_index++ > $_count ? ' class="last"' : '') ?> id="order-item-row-<?php echo $_item->getId() ?>">
                <td>
                    <?php echo $this->htmlEscape($_item->getName()) ?>
                    <?php echo $this->htmlEscape($_item->getDescription()) ?>
                </td>
                <td><?php echo $this->htmlEscape($_item->getSku()) ?></td>
                <td class="a-right nowrap"><?php echo $_order->formatPrice($_item->getPrice()) ?> </td>
                <td><?php echo $_item->getQty()*1 ?></td>
                <td class="a-right"><?php echo $_order->formatPrice($_item->getRowTotal()) ?></td>
                <td class="a-right"><?php echo $_order->formatPrice($_item->getTaxAmount()) ?></td>
                <td class="a-right"><?php echo $_order->formatPrice(-$_item->getDiscountAmount()) ?></td>
                <td class="last a-right nowrap">
                    <?php echo $_order->formatPrice($_item->getRowTotal()-$_item->getDiscountAmount()+$_item->getTaxAmount()) ?>
                </td>
            </tr>
        <?php endforeach; ?>

    </tbody>
    <tfoot>
        <?php echo $this->getTotalsHtml($_creditmemo);?>
    </tfoot>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php endforeach; ?>
<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back to My Orders') ?></a>
</div>
