<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php  $_order = $this->getOrder() ?>
<div class="page-head">
     <h4><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h4>
</div>
<div class="account-order-view">
        <div class="col2-set col3-alt-set content">
            <div class="col-1">
                 <?php echo $this->formatDate($_order->getCreatedAtStoreDate(), 'long') ?>
            </div>
            <div class="col-2 a-right">
                <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                    <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-cart"><?php echo $this->__('Reorder') ?></a>
                <?php endif ?>
         </div>
         </div><div class="clear bottom-space"></div>
    <?php echo $this->getStatusHistoryRssUrl($_order) ?>
<!--    <div class="order-access">
        <div class="order-info">
            <table cellspacing="0" class="shopping-cart checkout-review">
                <thead>
                    <tr>
                        <th class="a-left"><?php echo $this->__('About This Order:') ?></th>
                    </tr>
                </thead> 
                <tr>
                    <td style="border:0;">
                        <ul>
                        <?php $_links = $this->getLinks(); ?>
                            <?php foreach ($_links as $_link): ?>
                            <?php if($_link->getUrl()): ?>
                                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                            <?php else: ?>
                                <li class="selected"><?php echo $_link->getLabel() ?></li>
                            <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </td>
                </tr>
            </table>
        </div>
    </div> -->
<?php if (!$_order->getIsVirtual()): ?>
        <div class="page-head">
            <h4><?php echo $this->__('Shipping Address') ?></h4>
        </div><div class="content">
            <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
        </div>
        <div class="page-head">
            <h4><?php echo $this->__('Shipping Method') ?></h4>
        </div><div class="content">
            <?php if ($_order->getShippingDescription()): ?>
                <?php echo $_order->getShippingDescription() ?>
            <?php else: ?>
                <?php echo $this->helper('sales')->__('No shipping information available'); ?>
            <?php endif; ?>
        </div>
<?php endif; ?>
        <div class="page-head">
            <h4><?php echo $this->__('Billing Address') ?></h4>
        </div><div class="content">
            <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
        <div class="page-head">
            <h4><?php echo $this->__('Payment Method') ?></h4>
        </div><div class="content">
            <?php echo $this->getPaymentInfoHtml() ?>
        </div>
</div>