<div class="block block-tags">
	<div class="block-title">
        <strong><span>All Category</span></strong>
    </div>
	<div class="nav1">
	<?php $_categories=$this->getStoreCategories(); ?>
			<ul>
					<?php 
					$i=0; 
					$a='leftnav';
					foreach ($_categories as $_category){?>				
					<?php $i++;if ($i>=1){ if($_category->getIsActive()): ?>
						<li class="<?php echo "$a"?>">
						<h2>
						<a href="<?php echo $this->getCategoryUrl($_category)?>"><?php echo $_category->getName()?></a>
						</h2>
							<ul >
							<?php 
							$e=0;	
							$t='b_top';
							foreach($_category->getChildren() as $_childCategory){?>
							<?php $e++; if($e>=1) { if($_childCategory->getIsActive()) :?>  

							<li class="<?php if($e==1){echo "$t";} else {echo " ";} ?>">
							<h2>
								<a href="<?php echo $this->getCategoryUrl($_childCategory)?>"><?php echo $_childCategory->getName()?></a>
							</h2>
								<ul >
								<?php 
								$m=0;	
								$j='j_top';
								foreach($_childCategory->getChildren() as $_cchildCategory){?>
								<?php $m++; if($m>=1) { if($_cchildCategory->getIsActive()) :?> 
									<li class="<?php if($m==1){echo "$j";}else{echo" ";} ?>">
									<h2>
										<a href="<?php echo $this->getCategoryUrl($_cchildCategory)?>"><?php echo $_cchildCategory->getName()?></a>
									</h2>
									</li>
								 <?php endif;?>
								 <?php } } ?>
								</ul>
							</li>			
 							<?php endif;?>
							<?php } } ?>
							</ul> 
						</li>
					<?php endif; ?>	
					<?php } } ?> 
			</ul>
	</div>
<div style="clear:both"></div>
</div>
