<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>


<div class="page-head">
    <h4><?php echo $this->getTitle() ?></h4>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="content">
<?php echo $this->getChildHtml('')?>
</div>

<div class="buttons-set">
    <p class="back-link">
        <a href="<?php echo $this->getUrl('customer/account/index')?>">
            <small>&laquo; </small>  <?php echo $this->__('Back') ?>
        </a>
    </p>
</div>
