<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Check
 */
?>
<?php $card = $this->getCard() ?>
<?php if ($card->getId()): ?>
    <div class="gift-card-info">
        <p><?php echo $this->__("Gift Card: %s", '<strong class="giftcard-number">' . $card->getCode() . '</strong>'); ?></p>
        <p><?php echo $this->__('Current Balance: %s', '<strong>' . Mage::helper('core')->currency($card->getBalance()) . '</strong>'); ?></p>
        <?php if ($card->getDateExpires()): ?>
            <p><?php echo $this->__('Expires: %s', '<strong>' . $this->formatDate($card->getDateExpires(), 'short') . '</strong>'); ?></p>
        <?php endif; ?>
    </div>
<?php else: ?>
    <p class="error-msg"><?php echo $this->__('Wrong or expired Gift Card Code.'); ?></p>
<?php endif; ?>
