<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>

<div class="box one-page-checkout-progress">
        <h3><?php echo $this->__('Your Checkout Progress') ?></h3>
    <ol>
    <?php if($this->getCheckout()->getStepData('billing', 'complete')): ?>
        <li>
            <h4 class="complete"><?php echo $this->__('Billing Address') ?><span class="separator">|</span><a href="#billing" onclick="checkout.accordion.openSection('opc-billing');return false;"><?php echo $this->__('Change') ?></a></h4>
            <div class="content">
                <address><?php echo $this->getBilling()->format('html') ?></address>
            </div>
        </li>
    <?php else: ?>
        <li>
            <h4><?php echo $this->__('Billing Address') ?></h4>
        </li>
    <?php endif ?>

    <?php if($this->getCheckout()->getStepData('shipping', 'complete')): ?>
        <li>
            <h4 class="complete"><?php echo $this->__('Shipping Address') ?><span class="separator">|</span><a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a></h4>
            <div class="content">
                <address><?php echo $this->getShipping()->format('html') ?></address>
            </div>
        </li>
    <?php else: ?>
        <li>
            <h4><?php echo $this->__('Shipping Address') ?></h4>
        </li>
    <?php endif ?>

    <?php if($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
        <li>
            <h4 class="complete"><?php echo $this->__('Shipping Method') ?><span class="separator">|</span><a href="#shipping_method" onclick="checkout.accordion.openSection('opc-shipping_method');return false;"><?php echo $this->__('Change') ?></a></h4>
            <div class="content">
            <?php if ($this->getShippingMethod()): ?>
                <?php echo $this->getShippingDescription() ?>:

                <?php $_excl = $this->getShippingPriceExclTax(); ?>
                <?php $_incl = $this->getShippingPriceInclTax(); ?>
                <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                    <?php echo $_incl; ?>
                <?php else: ?>
                    <?php echo $_excl; ?>
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                <?php endif; ?>

            <?php else: ?>
                <?php echo $this->__('Shipping method has not been selected yet') ?>
            <?php endif ?>
            </div>
        </li>
    <?php else: ?>
        <li>
            <h4><?php echo $this->__('Shipping Method') ?></h4>
        </li>
    <?php endif ?>

    <?php if($this->getCheckout()->getStepData('payment', 'complete')): ?>
        <li>
            <h4 class="complete"><?php echo $this->__('Payment Method') ?><span class="separator">|</span><a href="#payment" onclick="checkout.accordion.openSection('opc-payment');return false;"><?php echo $this->__('Change') ?></a></h4>
            <div class="content">
                <?php echo $this->getPaymentHtml() ?>
            </div>
        </li>
    <?php else: ?>
        <li>
            <h4><?php echo $this->__('Payment Method') ?></h4>
        </li>
    <?php endif ?>
    </ol>
</div>
