<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php if( ($_additional = $this->getAdditionalData()) && (Mage::getStoreConfig('awmobile/product_page/catalog_additional_data')) ): ?>
<div class="collateral-box attribute-specs">
    <br />
    <div class="head">
        <h4><?php echo $this->__('Additional data') ?></h4>
    </div>
    <table cellspacing="0" class="data-table" id="product-attribute-specs-table">
    <?php foreach ($_additional as $_data): ?>
    <tr>
        <td class="label"><?php echo $_data['label'] ?></td>
        <td class="data"><?php echo $_data['value'] ?></td>
    </tr>
    <?php endforeach; ?>
    </table>
    <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
</div>
<?php endif;?>
