<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php $_product = $this->getProduct() ?>

<div class="product-image prof"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(85, 85); ?>" width="85" height="85" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></div>
<div class="product-image land"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(133, 133); ?>" width="133" height="133" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></div>
