<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Tax
 * @see Mage_Tax_Block_Checkout_Tax
 */
?>
<?php
    $_value = $this->getTotal()->getValue();
    $_style = $this->getTotal()->getStyle();
?>
<?php global $taxIter; $taxIter++; ?>
<?php if ($this->helper('tax')->displayFullSummary() && $_value!=0): ?>
<?php $isTop = 1; ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>

        <?php foreach ($rates as $rate): ?>
        <tr class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
            <td class="a-right" style="<?php echo $_style ?>" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $rate['title']; ?>
                <?php if ($rate['percent']): ?>
                    (<?php echo $rate['percent']; ?>%)
                <?php endif; ?>
                <br />
            </td>
            <?php if ($isFirst): ?>
                <td style="<?php echo $_style ?>" class="a-right" rowspan="<?php echo count($rates); ?>">
                    <?php echo $this->helper('checkout')->formatPrice($amount); ?>
                </td>
            <?php endif; ?>
        </tr>
        <?php $isFirst = 0; ?>
        <?php $isTop = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif;?>
<tr <?php if ($this->helper('tax')->displayFullSummary() && $_value!=0): ?> class="summary-total" onclick="expandDetails(this, '.summary-details-<?php echo $taxIter;?>')"<?php endif; ?>>
    <td style="<?php echo $_style ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <div class="summary-collapse"><?php echo $this->getTotal()->getTitle() ?></div>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle() ?>
        <?php endif;?>
    </td>
    <td style="<?php echo $_style ?>" class="a-right"><?php echo $this->helper('checkout')->formatPrice($_value) ?></td>
</tr>
