<div id="text_info">
	 
	 <h3 class="in_1em"><a name="#a"></a>Why Shop at OS-STORE?</h3>
		<ul>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/store.png') ?>" /></div>
		<div style="float:right;width:88%"><b>Easy & Safe Online Shopping</b><br /> 
		<span>Multiple methods of payment and simple shopping process</span></div>
		</li>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/offter.png') ?>" /></div>
		<div style="float:right;width:88%"><b>More Choices for A Better Life 
Safety and Quick Shopping</b> <br />
<span>Full Products info & Special resourcing, even only OS-STore offer.</span></div>
		</li>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/os.png') ?>" /></div>
		<div style="float:right;width:88%"><b>Safe & Quick Payment </b><br />
		<span>Easy, Fast, Secure payment technology keeping your information safe at all times.</span></div>
		</li>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/fly.png') ?>" /></div>
		<div style="float:right;width:88%"><b>Fast Delivery Around The Globe</b> <br />
		<span>Partnering with internationally trusted logistic service providers, The fastest delivery within 3days.</span></div>
		</li>
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/high.png') ?>" /></div>
		<div style="float:right;width:88%"><b>High Quality With Global Standards</b><br />
		<span>Products undergoes an extensive testing and quality control procedure in each item.</span></div>
		</li>	
		<li class="li_width">
		<div style="float:left;width:12%"><img style="vertical-align:middle" src="<?php echo $this->getSkinUrl('images/life.png') ?>" /></div>
		<div style="float:right;width:88%"><b>Join OS-STore to your life
		 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="button" class="button" onclick="window.location='<?php echo $this->getUrl('customer/account/login') ?>';">
		<span><span><?php echo $this->__('Join Us') ?></span></span></button>
		</b><br />
		<span>Registering to be a membe and take more Services, information, Discount we offer to you.</span></div>
		</li>
		</ul>
		
		
</div>

