<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $action ?>" method="post" id="form-validate">
    <fieldset class="group-select">
        <legend><?php echo $this->__('Change Account Password') ?></legend>
        <ul>
            <li>
                <div><label for="current_password"><?php echo $this->__('Current Password') ?> <span class="required">*</span></label></div>
                <div class="input-box"><input type="password" class="required-entry input-text" name="current_password" id="current_password" /></div>
            </li>
            <li>
                <div><label for="password"><?php echo $this->__('New Password') ?> <span class="required">*</span></label></div>
                <div class="input-box"><input type="password" class="required-entry validate-password input-text" name="password" id="password" /></div>
                <div><label for="confirmation"><?php echo $this->__('Confirm New Password') ?> <span class="required">*</span></label></div>
                <div class="input-box"><input type="password" class="required-entry validate-cpassword input-text" name="confirmation" id="confirmation" /></div>
            </li>
        </ul>
    </fieldset>
    <div class="button-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button class="form-button" type="submit"><span><?php echo $this->__('Save Password') ?></span></button>
    </div>
    </form>
    <script type="text/javascript">
        var dataForm = new VarienForm('form-validate');
    </script>
