<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<h2>Address Book</h2>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<table cellspacing="0" width="100%">
    <tr>
        <td style="width:50%;"><h3>Default</h3>
            <table width="100%" cellspacing="0">
            <?php if(!empty($primaryAddresses)): ?>
                <?php foreach($primaryAddresses as $_address): ?>
                <tr>
                    <td>
                    <address>
                        <?php echo nl2br($_address->toString("{{firstname}} {{lastname}}\n{{street}}\n{{city}}, {{regionName}} {{postcode}}\nT: {{telephone}}")) ?>
                    </address>
                    <p>
                        <strong><a href="<?php echo $this->getUrl('customer/address/form', array('address'=>$_address->getAddressId())) ?>" class="red-link"><?php echo $this->__('Edit Address') ?></a></strong>
                    </p>
                    </td>
                </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td>
                        <p><?php echo $this->__('You have no default entries in your address book.') ?></p>
                    </td>
                </tr>
            <?php endif ?>
            </table>
        </td>
        <td style="width:50%;"><h3><?php echo $this->__('Additional Address Entries') ?></h3>
            <table width="100%" cellspacing="0">
            <?php if(!empty($alternativeAddresses)): ?>
                <?php foreach($alternativeAddresses as $_address): ?>
                <tr>
                    <td>
                    <address>
                        <?php echo nl2br($_address->toString("{{firstname}} {{lastname}}\n{{street}}\n{{city}}, {{regionName}} {{postcode}}\nT: {{telephone}}")) ?>
                    </address>
                    <p>
                        <strong><a href="<?php echo $this->getUrl('customer/address/form', array('address'=>$_address->getAddressId())) ?>" class="red-link"><?php echo $this->__('Edit Address') ?></a></strong><span class="separator">&nbsp;|&nbsp;</span><strong><a href="#" onclick="return deleteAddress('<?php echo $_address->getAddressId() ?>');" class="red-link"><?php echo $this->__('Delete Address') ?></a></strong>
                    </p>
                    </td>
                </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td>
                        <p><?php echo $this->__('You have no additional entries in your address book.') ?></p>
                    </td>
                </tr>
            <?php endif ?>
            </table>
        </td>
    </tr>
</table>
<div class="buttons-container">
    <a class="button grey left"  title="Go back" href="<?php echo Mage::getUrl('customer/account');?>"><span class="nowrap"><?php echo $this->__('Back');?></span></a>
    <input type="button" onclick="window.location='<?php echo $this->getUrl('customer/address/form') ?>';" value="<?php echo $this->__('New Address') ?>" class="input-button" />
</div>
<script type="text/javascript">
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getUrl("customer/address/delete") ?>address/'+addressId;
        }
        return false;
    }
</script>
