<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php
    $_order  = $this->getOrder();
    $_source = $this->getSource();
    $_fullInfo = $_source->getFullTaxInfo();
    global $taxIter; $taxIter++;
?>
<?php  ?>

<?php if ($this->displayFullSummary()): ?>
<?php $isTop = 1; ?>
    <?php if ($_fullInfo) foreach ($_fullInfo as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php
            $percent    = $info['percent'];
            $amount     = $info['amount'];
            $rates      = $info['rates'];
            $isFirst    = 1;
        ?>
        <?php foreach ($rates as $rate): ?>
        <tr class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>"<?php if (!$this->getIsPlaneMode()):?> style="display:none;"<?php endif;?>>
            <td <?php echo $this->getLabelProperties()?>>
                <?php echo $rate['title']; ?>
                <?php if ($rate['percent']): ?>
                    (<?php echo $rate['percent']; ?>%)
                <?php endif; ?>
                <br />
            </td>
            <?php if ($isFirst): ?>
                <td <?php echo $this->getValueProperties()?> rowspan="<?php echo count($rates); ?>">
                    <?php echo $_order->formatPrice($amount); ?>
                </td>
            <?php endif; ?>
        </tr>
        <?php $isFirst = 0; ?>
        <?php $isTop = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif;?>

<?php if ($this->displayFullSummary() && $_fullInfo && !$this->getIsPlaneMode()): ?>
<tr class="summary-total" onclick="expandDetails(this, '.summary-details-<?php echo $taxIter;?>')">
<?php elseif ($this->displayFullSummary() && $_fullInfo && $this->getIsPlaneMode()): ?>
<tr class="show-details">
<?php else: ?>
<tr>
<?php endif; ?>
    <td <?php echo $this->getLabelProperties()?>>
        <?php if ($this->displayFullSummary()): ?>
            <div class="summary-collapse"><?php echo $this->__('Tax'); ?></div>
        <?php else: ?>
            <?php echo $this->__('Tax'); ?>
        <?php endif;?>
    </td>
    <td <?php echo $this->getValueProperties()?>><?php echo $_order->formatPrice($_source->getTaxAmount()) ?></td>
</tr>
