<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>
<?php if($this->getTitle()): ?>
    <div class="page-head">
        <h3><?php echo $this->getTitle() ?></h3>
    </div>
<?php endif; ?>
<div class="account-page">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
        <?php echo $this->getBlockHtml('formkey')?>
        <fieldset class="group-select bottom-space">
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h4 class="legend"><?php echo $this->__('Contact Information') ?></h4>
            <ul class="form-list">
                <li>
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getCustomer())->toHtml() ?>
                </li>
                <li>
                        <div><label for="company"><?php echo $this->__('Company') ?></label></div>
                        <div class="input-box"><input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" class="input-text" /></div>
                </li>
                <li>
                        <div><label for="telephone"><?php echo $this->__('Telephone') ?> <span class="required">*</span></label></div>
                        <div class="input-box"><input type="text" name="telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="required-entry input-text" id="telephone" /></div>
                </li>
                <li>
                        <div><label for="fax"><?php echo $this->__('Fax') ?></label></div>
                        <div class="input-box"><input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" class="input-text" /></div>
                </li>
            </ul>
        </fieldset>

        <fieldset class="group-select">
            <h4 class="legend"><?php echo $this->__('Address') ?></h4>
            <ul class="form-list bottom-space">
                <li>
                        <div><label for="street_1"><?php echo $this->__('Street Address') ?> <span class="required">*</span></label></div>
                        <div class="input-box"><input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="required-entry input-text" /></div>
                </li>
                <li>
                        <div></div>
                        <div class="input-box"><input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" title="<?php echo $this->__('Street Address %s', 2) ?>" id="street_2" class="input-text" /></div>
                </li>
                <li>
                        <div><label for="city"><?php echo $this->__('City') ?> <span class="required">*</span></label></div>
                        <div class="input-box"><input type="text" name="city" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="required-entry input-text" id="city" /></div>
                </li>
                <li>
                        <div><label for="region_id"><?php echo $this->__('State/Province') ?><span class="required">*</span></label></div>
                        <div class="select190inner">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                                $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none" />
                        </div>
                </li>
                <li>
                        <div><label for="zip"><?php echo $this->__('Zip/Postal Code') ?> <span class="required">*</span></label></div>
                        <div class="input-box"><input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="validate-zip-international required-entry input-text" /></div>
                </li>
                <li>
                        <div><label for="country"><?php echo $this->__('Country') ?> <span class="required">*</span></label></div>
                        <div class="select190inner"><?php echo $this->getCountryHtmlSelect() ?></div>
                </li>
                <li>
                    <?php if($this->isDefaultBilling()): ?>
                        <strong><?php echo $this->__('Default Billing Address') ?></strong>
                    <?php elseif($this->canSetAsDefaultBilling()): ?>
                        <input type="checkbox" id="primary_billing" name="default_billing" value="1" />&nbsp;
                        <label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                    <?php else: ?>
                        <input type="hidden" name="default_billing" value="1" />
                    <?php endif; ?>
                </li>
                <li>
                    <?php if($this->isDefaultShipping()): ?>
                        <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                    <?php elseif($this->canSetAsDefaultShipping()): ?>
                        <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" />&nbsp;
                        <label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                    <?php else: ?>
                        <input type="hidden" name="default_shipping" value="1" />
                    <?php endif; ?>
                </li>
            </ul>
        </fieldset>
            <div class="a-center bottom-space">
                <div class="form-buttons">
                    <button class="form-button" type="submit"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
                </div>
            </div>
    </form>
        <a class="button grey left"  title="Go back" href="<?php echo Mage::getUrl('customer/account');?>"><span class="nowrap"><span><?php echo $this->__('Back');?></span></span></a>
</div>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
</script>
